### ISSUE TITLE
Change max length for participant name field in serializer 

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#169] opened 2019-09-04 19:04 UTC
Change value from 5 to 3

**Comment by magul** [comment] 2019-09-18 17:38
MIN instead of MAX? @OtisRed ?

**Comment by ngiersz** [comment] 2019-10-07 19:01
It's the same topic as issue #146

**Comment by magul** [comment] 2019-10-07 19:02
Closing as duplicate of #146.

**Closed by magul** 2019-10-07 19:02 UTC
Labels: For beginners, backend
